apiVersion: apps/v1
kind: Deployment
metadata:
    name: celery-flower
    labels:
        pod: celery-flower
spec:
    replicas: 1
    selector:
        matchLabels:
            pod: celery-flower
    template:
        metadata:
            labels:
                pod: celery-flower
        spec:
            containers:
                - name: celery-flower
                  image: aitoyregistry.azurecr.io/aitoy:latest
                  command:
                      - poetry
                      - run
                      - celery
                      - "-A"
                      - "app.celery.worker.celery_app"
                      - flower
                      - "--basic_auth=$(CELERY_FLOWER_USER):$(CELERY_FLOWER_PASSWORD)"
                  ports:
                      - containerPort: 5555
                  resources:
                      limits:
                          cpu: 100m
                  envFrom:
                      - secretRef:
                            name: fastapi-prod-env

---
apiVersion: v1
kind: Service
metadata:
    name: flower-service
spec:
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 80
          targetPort: 5555
    selector:
        pod: celery-flower
