apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
    name: starmoon
spec:
    routes:
        - kind: Rule
          match: Host(`api.starmoon.app`)
          services:
              - name: starmoon-service
                port: 80
    tls:
        certResolver: default
